name: main

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: github.head_ref
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  documentation:
    runs-on: ubuntu-latest
    name: documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.8.3

      - name: generate documentation
        run: make documentation-ci

      - name: check docs diff
        run: exit $(git status --porcelain doc | wc -l | tr -d " ")

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        neovim_version:
          - v0.10.1
          - nightly

    steps:
      - uses: actions/checkout@v4

      - run: date +%F > todays-date

      - name: restore cache for today's nightly.
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: run tests
        run: make test-ci
